############################
## CHANGE THESE
############################

baseURL: 'https://ZoeLiu1999.github.io/mysite'
title: mysite

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


